
/* Drop Tables */

DROP TABLE ANSWER_OF_USER;
DROP TABLE DEPOSIT;
DROP TABLE FIXED_DEPOSIT;
DROP TABLE FIXED_DEPOSIT_ACCOUNT;
DROP TABLE FOREIGN_CURRENCY_DEPOSIT;
DROP TABLE FOREIGN_CURRENCY_DEPOSIT_ACCOUT;
DROP TABLE FUND_ORDER;
DROP TABLE FUND_ACCOUNT;
DROP TABLE TRANSFER;
DROP TABLE SAVINGS_ACCOUNT;
DROP TABLE BRANCH;
DROP TABLE BUSINESS_DAY;
DROP TABLE BUYABLE_FUND_BY_RISK_ANSWER;
DROP TABLE CREDNTIAL;
DROP TABLE FUND_FEE_RATIO;
DROP TABLE PROSPECTUS;
DROP TABLE FUND;
DROP TABLE FINANCIAL_INSTITUTION;
DROP TABLE RISK_ANSWER;
DROP TABLE RISK_QUESTION;
DROP TABLE USR;




/* Create Tables */

CREATE TABLE ANSWER_OF_USER
(
	QUESTION_ID varchar(4) NOT NULL,
	ANSWER_ID varchar(4) NOT NULL,
	USER_ID varchar(8) NOT NULL,
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (QUESTION_ID, ANSWER_ID, USER_ID),
	UNIQUE (QUESTION_ID, ANSWER_ID, USER_ID)
);


CREATE TABLE BRANCH
(
	FINANCIAL_CODE varchar(4) NOT NULL,
	BRANCH_ID varchar(6) NOT NULL,
	BRANCH_NAME varchar(512),
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (FINANCIAL_CODE, BRANCH_ID),
	UNIQUE (FINANCIAL_CODE, BRANCH_ID)
);


CREATE TABLE BUSINESS_DAY
(
	YYYYMMDD varchar(8) NOT NULL,
	IS_BUSINESS_DAY boolean,
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (YYYYMMDD)
);


CREATE TABLE BUYABLE_FUND_BY_RISK_ANSWER
(
	QUESTION_ID varchar(4) NOT NULL,
	ANSWER_ID varchar(4) NOT NULL,
	FUND_ID varchar(8) NOT NULL,
	CAN_BY boolean,
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (QUESTION_ID, ANSWER_ID, FUND_ID),
	UNIQUE (QUESTION_ID, ANSWER_ID, FUND_ID)
);


CREATE TABLE CREDNTIAL
(
	USER_ID varchar(8) NOT NULL,
	CREDENTIAL_KEY_TYPE varchar(50) NOT NULL,
	CREDENTIAL_KEY varchar(50),
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (USER_ID, CREDENTIAL_KEY_TYPE),
	UNIQUE (USER_ID, CREDENTIAL_KEY_TYPE)
);


CREATE TABLE DEPOSIT
(
	TRADE_ID varchar(128) NOT NULL UNIQUE,
	USER_ID varchar(8) NOT NULL,
	FINANCIAL_CODE varchar(4) NOT NULL,
	BRANCH_ID varchar(6) NOT NULL,
	ACCOUNT_NO varchar(7) NOT NULL,
	BALANCE decimal,
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (TRADE_ID, USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO),
	UNIQUE (TRADE_ID, USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO)
);


CREATE TABLE FINANCIAL_INSTITUTION
(
	FINANCIAL_CODE varchar(4) NOT NULL,
	FINANCIAL_INSTITUTION_NAME varchar(512),
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (FINANCIAL_CODE)
);


CREATE TABLE FIXED_DEPOSIT
(
	TRADE_ID varchar(128) NOT NULL UNIQUE,
	USER_ID varchar(8) NOT NULL,
	FINANCIAL_CODE varchar(4) NOT NULL,
	BRANCH_ID varchar(6) NOT NULL,
	ACCOUNT_NO varchar(7) NOT NULL,
	FIXED_ACCOUNT_NO varchar(7) NOT NULL,
	FIXED_DEPOSIT_TYPE varchar(50),
	TRADE_START_DATE timestamp(29),
	MATURITY_DAY varchar(8),
	BALANCE decimal,
	RATIO decimal,
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (TRADE_ID, USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FIXED_ACCOUNT_NO)
);


CREATE TABLE FIXED_DEPOSIT_ACCOUNT
(
	USER_ID varchar(8) NOT NULL,
	FINANCIAL_CODE varchar(4) NOT NULL,
	BRANCH_ID varchar(6) NOT NULL,
	ACCOUNT_NO varchar(7) NOT NULL,
	CIF_NO varchar(7),
	FIXED_ACCOUNT_NO varchar(7) NOT NULL,
	ACCOUNT_TYPE varchar(50),
	ACCOUNT_START_DATE timestamp(29),
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FIXED_ACCOUNT_NO),
	UNIQUE (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FIXED_ACCOUNT_NO)
);


CREATE TABLE FOREIGN_CURRENCY_DEPOSIT
(
	TRADE_ID varchar(128) NOT NULL UNIQUE,
	USER_ID varchar(8) NOT NULL,
	FINANCIAL_CODE varchar(4) NOT NULL,
	BRANCH_ID varchar(6) NOT NULL,
	ACCOUNT_NO varchar(7) NOT NULL,
	FOREIGN_CURRENCY_ACCOUNT_NO varchar(7) NOT NULL,
	FOREIGN_CURRENCY_DEPOSIT_TYPE varchar(50),
	BALANCE decimal,
	TRADE_START_DATE timestamp(29),
	MATURITY_DAY varchar(8),
	RATIO decimal,
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (TRADE_ID, USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FOREIGN_CURRENCY_ACCOUNT_NO),
	UNIQUE (TRADE_ID, USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FOREIGN_CURRENCY_ACCOUNT_NO)
);


CREATE TABLE FOREIGN_CURRENCY_DEPOSIT_ACCOUT
(
	USER_ID varchar(8) NOT NULL,
	FINANCIAL_CODE varchar(4) NOT NULL,
	BRANCH_ID varchar(6) NOT NULL,
	ACCOUNT_NO varchar(7) NOT NULL,
	CIF_NO varchar(7),
	FOREIGN_CURRENCY_ACCOUNT_NO varchar(7) NOT NULL,
	ACCOUNT_TYPE varchar(50),
	CURRENCY varchar(50),
	ACCOUNT_START_DATE timestamp(29),
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FOREIGN_CURRENCY_ACCOUNT_NO),
	UNIQUE (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FOREIGN_CURRENCY_ACCOUNT_NO)
);


CREATE TABLE FUND
(
	FUND_ID varchar(8) NOT NULL,
	FUND_NAME varchar(512),
	TRADE_START_DAY varchar(8),
	FINANCIAL_CODE varchar(4) NOT NULL,
	TRADE_START_DATE timestamp(29),
	MATURITY_DAY varchar(8),
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (FUND_ID)
);


CREATE TABLE FUND_ACCOUNT
(
	USER_ID varchar(8) NOT NULL,
	FINANCIAL_CODE varchar(4) NOT NULL,
	BRANCH_ID varchar(6) NOT NULL,
	ACCOUNT_NO varchar(7) NOT NULL,
	FUND_ACCOUNT_NO varchar(7) NOT NULL,
	ACCOUNT_TYPE varchar(50),
	ACCOUNT_START_DATE timestamp(29),
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FUND_ACCOUNT_NO),
	UNIQUE (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FUND_ACCOUNT_NO)
);


CREATE TABLE FUND_FEE_RATIO
(
	FUND_ID varchar(8) NOT NULL,
	VALID_START_DAY varchar(8) NOT NULL,
	FEE_RATIO decimal,
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (FUND_ID, VALID_START_DAY),
	UNIQUE (FUND_ID, VALID_START_DAY)
);


CREATE TABLE FUND_ORDER
(
	TRADE_ID varchar(128) NOT NULL UNIQUE,
	USER_ID varchar(8) NOT NULL,
	FINANCIAL_CODE varchar(4) NOT NULL,
	BRANCH_ID varchar(6) NOT NULL,
	ACCOUNT_NO varchar(7) NOT NULL,
	FUND_ACCOUNT_NO varchar(7) NOT NULL,
	FUND_ID varchar(8) NOT NULL,
	ORDER_TYPE varchar(50),
	AMOUNT decimal,
	TRADE_START_DATE timestamp(29),
	LAST_UPDATED_AT timestamp(29),
	PRIMARY KEY (TRADE_ID, USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FUND_ACCOUNT_NO, FUND_ID)
);


CREATE TABLE PROSPECTUS
(
	FUND_ID varchar(8) NOT NULL,
	PROSPECTUS_NO int NOT NULL,
	FILE_PATH varchar(512),
	IS_VALID boolean,
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (FUND_ID, PROSPECTUS_NO),
	UNIQUE (FUND_ID, PROSPECTUS_NO)
);


CREATE TABLE RISK_ANSWER
(
	QUESTION_ID varchar(4) NOT NULL,
	ANSWER_ID varchar(4) NOT NULL,
	ANSWER varchar(1024),
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (QUESTION_ID, ANSWER_ID),
	UNIQUE (QUESTION_ID, ANSWER_ID)
);


CREATE TABLE RISK_QUESTION
(
	QUESTION_ID varchar(4) NOT NULL,
	QUESTION varchar(1024),
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (QUESTION_ID)
);


CREATE TABLE SAVINGS_ACCOUNT
(
	USER_ID varchar(8) NOT NULL,
	FINANCIAL_CODE varchar(4) NOT NULL,
	BRANCH_ID varchar(6) NOT NULL,
	CIF_NO varchar(7),
	ACCOUNT_NO varchar(7) NOT NULL,
	ACCOUNT_TYPE varchar(50),
	TOTAL_AMOUNT decimal,
	ACCOUNT_START_DATE timestamp(29),
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO),
	UNIQUE (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO)
);


CREATE TABLE TRANSFER
(
	TRADE_ID varchar(128) NOT NULL UNIQUE,
	USER_ID varchar(8) NOT NULL,
	FINANCIAL_CODE varchar(4) NOT NULL,
	BRANCH_ID varchar(6) NOT NULL,
	ACCOUNT_NO varchar(7) NOT NULL,
	TRANSFER_TO_FINANCIAL_CODE varchar(4),
	TRANSFER_TO_BRANCHI_ID varchar(6),
	TRANSFER_TO_ACCOUNT_NO varchar(7),
	AMOUNT decimal,
	TRANSFER_TRADE_DAY varchar(8),
	FEE decimal,
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (TRADE_ID, USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO),
	UNIQUE (TRADE_ID, USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO)
);


CREATE TABLE USR
(
	USER_ID varchar(8) NOT NULL,
	FIRST_NAME varchar(50),
	LAST_NAME varchar(50),
	LOGIN_ID varchar(32) UNIQUE,
	BIRTHDAY varchar(8),
	SEX varchar(50),
	LAST_UPDATED_AT timestamp(29),
	VER int,
	PRIMARY KEY (USER_ID)
);



/* Create Foreign Keys */

ALTER TABLE SAVINGS_ACCOUNT
	ADD FOREIGN KEY (FINANCIAL_CODE, BRANCH_ID)
	REFERENCES BRANCH (FINANCIAL_CODE, BRANCH_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BRANCH
	ADD FOREIGN KEY (FINANCIAL_CODE)
	REFERENCES FINANCIAL_INSTITUTION (FINANCIAL_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FUND
	ADD FOREIGN KEY (FINANCIAL_CODE)
	REFERENCES FINANCIAL_INSTITUTION (FINANCIAL_CODE)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FIXED_DEPOSIT
	ADD FOREIGN KEY (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FIXED_ACCOUNT_NO)
	REFERENCES FIXED_DEPOSIT_ACCOUNT (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FIXED_ACCOUNT_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FOREIGN_CURRENCY_DEPOSIT
	ADD FOREIGN KEY (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FOREIGN_CURRENCY_ACCOUNT_NO)
	REFERENCES FOREIGN_CURRENCY_DEPOSIT_ACCOUT (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FOREIGN_CURRENCY_ACCOUNT_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BUYABLE_FUND_BY_RISK_ANSWER
	ADD FOREIGN KEY (FUND_ID)
	REFERENCES FUND (FUND_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FUND_FEE_RATIO
	ADD FOREIGN KEY (FUND_ID)
	REFERENCES FUND (FUND_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FUND_ORDER
	ADD FOREIGN KEY (FUND_ID)
	REFERENCES FUND (FUND_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE PROSPECTUS
	ADD FOREIGN KEY (FUND_ID)
	REFERENCES FUND (FUND_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FUND_ORDER
	ADD FOREIGN KEY (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FUND_ACCOUNT_NO)
	REFERENCES FUND_ACCOUNT (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO, FUND_ACCOUNT_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ANSWER_OF_USER
	ADD FOREIGN KEY (QUESTION_ID, ANSWER_ID)
	REFERENCES RISK_ANSWER (QUESTION_ID, ANSWER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE BUYABLE_FUND_BY_RISK_ANSWER
	ADD FOREIGN KEY (QUESTION_ID, ANSWER_ID)
	REFERENCES RISK_ANSWER (QUESTION_ID, ANSWER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE RISK_ANSWER
	ADD FOREIGN KEY (QUESTION_ID)
	REFERENCES RISK_QUESTION (QUESTION_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE DEPOSIT
	ADD FOREIGN KEY (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO)
	REFERENCES SAVINGS_ACCOUNT (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FIXED_DEPOSIT_ACCOUNT
	ADD FOREIGN KEY (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO)
	REFERENCES SAVINGS_ACCOUNT (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FOREIGN_CURRENCY_DEPOSIT_ACCOUT
	ADD FOREIGN KEY (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO)
	REFERENCES SAVINGS_ACCOUNT (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE FUND_ACCOUNT
	ADD FOREIGN KEY (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO)
	REFERENCES SAVINGS_ACCOUNT (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE TRANSFER
	ADD FOREIGN KEY (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO)
	REFERENCES SAVINGS_ACCOUNT (USER_ID, FINANCIAL_CODE, BRANCH_ID, ACCOUNT_NO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE ANSWER_OF_USER
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE CREDNTIAL
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SAVINGS_ACCOUNT
	ADD FOREIGN KEY (USER_ID)
	REFERENCES USR (USER_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



