spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql:
              BasicBinder: trace
          EnumType: trace
app:
domain:
  transfer:
    fee:
      high:
        for:
          other:
            financial:
              Institution: 432
          same:
            financial:
              Institution: 216
      low:
        for:
          other:
            financial:
              Institution: 216
          same:
            financial:
              Institution: 108


